manala:
  recipe: ops.role
  repository: /Users/loic/Ops/manala-recipes


gitignore: ""

ansible: 
  auto_tag: true
  cfg_lines: {}
  internal_roles: false
  inventory: site.yml
  privilege_escalation:
      become: true
      become_ask_pass: false
      become_method: sudo
      become_user: root

vagrant: 
  project_name: role-porter-run
  box: loic-roux-404/deb64-buster
  box_update: false
  box_version: null
  vb_guest_update: false
  domain: porter.test
  git: 
    org: loic-roux-404
    provider: github.com
  paths: 
    guest: /vagrant
    host: ./
    web: ""
  network: 
    dns: true
    fix_routing: true
    ip: null
    ports: []
    ssl:
        cert: null
        path: /etc/ssl
    type: public 
  ansible: 
    disabled: true
    inventory: ""
    playbook: ""
    playbook_version: master
    sub_playbook: site.yml
    type: local
    vars: {}
  fs: 
    opts:
        disabled: true
        ignored:
            - /**/.DS_Store
            - .git
            - .vagrant
            - .idea/
            - .vscode/
        rsync_auto: true
        smb_password: null
        smb_username: null
    type: rsync
  provider:  
    opts:
        cpus: "2"
        memory: "1024"
        natdnshostresolver1: "on"
    type: virtualbox
